// Generated by: agents/unity/shader-generator/agent.md
// Unity URP Unlit Shader — Holographic Scanline Effect
// Supports Unity 6 / URP 17+

Shader "Custom/HolographicScanline"
{
    Properties
    {
        _MainTex        ("Base Texture (optional)", 2D) = "white" {}
        _TintColor      ("Tint Color", Color) = (0.05, 0.15, 0.4, 0.75)
        _ScanlineFreq   ("Scanline Frequency", Range(10, 200)) = 60
        _ScanlineSpeed  ("Scanline Scroll Speed", Range(0, 5)) = 1.2
        _ScanlineBright ("Scanline Brightness", Range(0, 1)) = 0.15
        _EdgeGlow       ("Edge Glow Intensity", Range(0, 2)) = 0.6
        _EdgeFalloff    ("Edge Glow Falloff", Range(1, 10)) = 3.0
    }

    SubShader
    {
        Tags
        {
            "RenderType" = "Transparent"
            "Queue" = "Transparent"
            "RenderPipeline" = "UniversalPipeline"
        }

        Blend SrcAlpha OneMinusSrcAlpha
        ZWrite Off
        Cull Back

        Pass
        {
            Name "HolographicScanlinePass"

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma prefer_hlslcc gles
            #pragma exclude_renderers d3d11_9x

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"

            struct Attributes
            {
                float4 positionOS : POSITION;
                float2 uv         : TEXCOORD0;
            };

            struct Varyings
            {
                float4 positionHCS : SV_POSITION;
                float2 uv          : TEXCOORD0;
                float  normalizedY : TEXCOORD1;
            };

            TEXTURE2D(_MainTex);
            SAMPLER(sampler_MainTex);

            CBUFFER_START(UnityPerMaterial)
                float4 _MainTex_ST;
                half4  _TintColor;
                half   _ScanlineFreq;
                half   _ScanlineSpeed;
                half   _ScanlineBright;
                half   _EdgeGlow;
                half   _EdgeFalloff;
            CBUFFER_END

            Varyings vert(Attributes IN)
            {
                Varyings OUT;
                OUT.positionHCS = TransformObjectToHClip(IN.positionOS.xyz);
                OUT.uv = TRANSFORM_TEX(IN.uv, _MainTex);
                OUT.normalizedY = IN.positionOS.y + 0.5;
                return OUT;
            }

            half4 frag(Varyings IN) : SV_Target
            {
                half4 texColor = SAMPLE_TEXTURE2D(_MainTex, sampler_MainTex, IN.uv);

                float scanlinePhase = IN.uv.y * _ScanlineFreq
                                    - _Time.y * _ScanlineSpeed;
                half scanline = sin(scanlinePhase * 3.14159) * 0.5 + 0.5;
                scanline = pow(scanline, 4.0);
                scanline *= _ScanlineBright;

                half edgeMask = 1.0 - abs(IN.normalizedY * 2.0 - 1.0);
                edgeMask = 1.0 - pow(edgeMask, _EdgeFalloff);
                half edgeGlow = edgeMask * _EdgeGlow;

                half4 col = _TintColor;
                col.rgb += scanline + edgeGlow;
                col.rgb *= texColor.rgb;
                col.a = _TintColor.a * texColor.a;

                return col;
            }
            ENDHLSL
        }
    }
    FallBack Off
}
